export type Variant = "Regular" | "Medium" | "Semibold" | "Bold";

export type Size = 
	| "Display 2xl" 
	| "Display xl" 
	| "Display lg" 
	| "Display md"
	| "Display sm"
	| "Display xs"
	| "Text xl"
	| "Text lg"
	| "Text md"
	| "Text sm"
	| "Text xs";

export type Color =
	| "text-PRIMARY-Lighter"
	| "text-PRIMARY-Light"
	| "text-PRIMARY-Main"
	| "text-PRIMARY-Dark"
	| "text-PRIMARY-Darker"
	| "text-PRIMARY-Glass-8"
	| "text-PRIMARY-Glass-12"
	| "text-PRIMARY-Glass-16"
	| "text-PRIMARY-Glass-20"
	| "text-PRIMARY-Glass-24"
	| "text-PRIMARY-Glass-32"
	| "text-PRIMARY-Glass-40"
	| "text-PRIMARY-Glass-48"
	| "text-SECONDARY-Lighter"
	| "text-SECONDARY-Light"
	| "text-SECONDARY-Main"
	| "text-SECONDARY-Dark"
	| "text-SECONDARY-Darker"
	| "text-SECONDARY-Glass-8"
	| "text-SECONDARY-Glass-12"
	| "text-SECONDARY-Glass-16"
	| "text-SECONDARY-Glass-20"
	| "text-SECONDARY-Glass-24"
	| "text-SECONDARY-Glass-32"
	| "text-SECONDARY-Glass-40"
	| "text-SECONDARY-Glass-48"
	| "text-INFO-Lighter"
	| "text-INFO-Light"
	| "text-INFO-Main"
	| "text-INFO-Dark"
	| "text-INFO-Darker"
	| "text-INFO-Glass-8"
	| "text-INFO-Glass-12"
	| "text-INFO-Glass-16"
	| "text-INFO-Glass-20"
	| "text-INFO-Glass-24"
	| "text-INFO-Glass-32"
	| "text-INFO-Glass-40"
	| "text-INFO-Glass-48"
	| "text-SUCCESS-Lighter"
	| "text-SUCCESS-Light"
	| "text-SUCCESS-Main"
	| "text-SUCCESS-Dark"
	| "text-SUCCESS-Darker"
	| "text-SUCCESS-Glass-8"
	| "text-SUCCESS-Glass-12"
	| "text-SUCCESS-Glass-16"
	| "text-SUCCESS-Glass-20"
	| "text-SUCCESS-Glass-24"
	| "text-SUCCESS-Glass-32"
	| "text-SUCCESS-Glass-40"
	| "text-SUCCESS-Glass-48"
	| "text-WARNING-Lighter"
	| "text-WARNING-Light"
	| "text-WARNING-Main"
	| "text-WARNING-Dark"
	| "text-WARNING-Darker"
	| "text-WARNING-Glass-8"
	| "text-WARNING-Glass-12"
	| "text-WARNING-Glass-16"
	| "text-WARNING-Glass-20"
	| "text-WARNING-Glass-24"
	| "text-WARNING-Glass-32"
	| "text-WARNING-Glass-40"
	| "text-WARNING-Glass-48"
	| "text-ERROR-Lighter"
	| "text-ERROR-Light"
	| "text-ERROR-Main"
	| "text-ERROR-Dark"
	| "text-ERROR-Darker"
	| "text-ERROR-Glass-8"
	| "text-ERROR-Glass-12"
	| "text-ERROR-Glass-16"
	| "text-ERROR-Glass-20"
	| "text-ERROR-Glass-24"
	| "text-ERROR-Glass-32"
	| "text-ERROR-Glass-40"
	| "text-ERROR-Glass-48"
	| "text-GREY-100"
	| "text-GREY-200"
	| "text-GREY-300"
	| "text-GREY-400"
	| "text-GREY-500"
	| "text-GREY-600"
	| "text-GREY-700"
	| "text-GREY-800"
	| "text-GREY-900"
	| "text-GREY-Glass-8"
	| "text-GREY-Glass-12"
	| "text-GREY-Glass-16"
	| "text-GREY-Glass-20"
	| "text-GREY-Glass-24"
	| "text-GREY-Glass-32"
	| "text-GREY-Glass-40"
	| "text-GREY-Glass-48"
	| "text-GREY-Glass-56"
	| "text-GREY-Glass-64"
	| "text-GREY-Glass-72"
	| "text-GREY-Glass-80"
	| "text-BLACK-Main"
	| "text-BLACK-Glass-8"
	| "text-BLACK-Glass-12"
	| "text-BLACK-Glass-16"
	| "text-BLACK-Glass-24"
	| "text-BLACK-Glass-32"
	| "text-BLACK-Glass-40"
	| "text-BLACK-Glass-48"
	| "text-BLACK-Glass-56"
	| "text-BLACK-Glass-64"
	| "text-BLACK-Glass-72"
	| "text-BLACK-Glass-80"
	| "text-WHITE-Main"
	| "text-WHITE-Glass-8"
	| "text-WHITE-Glass-12"
	| "text-WHITE-Glass-16"
	| "text-WHITE-Glass-24"
	| "text-WHITE-Glass-32"
	| "text-WHITE-Glass-40"
	| "text-WHITE-Glass-48"
	| "text-WHITE-Glass-56"
	| "text-WHITE-Glass-64"
	| "text-WHITE-Glass-72"
	| "text-WHITE-Glass-80"
	| "text-Text-Dark-Primary"
	| "text-Text-Dark-Secondary"
	| "text-Text-Dark-Disabled"
	| "text-Text-Light-Primary"
	| "text-Text-Light-Secondary"
	| "text-Text-Light-Disabled"
	| "text-Background-Dark-Default"
	| "text-Background-Dark-Paper"
	| "text-Background-Dark-Neutral"
	| "text-Background-Light-Default"
	| "text-Background-Light-Paper"
	| "text-Background-Light-Neutral"
	| "text-Divider"
	| "text-Action-Dark-Active"
	| "text-Action-Dark-Hover"
	| "text-Action-Dark-Selected"
	| "text-Action-Dark-Focus"
	| "text-Action-Dark-Disabled"
	| "text-Action-Dark-Disabled-background"
	| "text-Action-Light-Active"
	| "text-Action-Light-Hover"
	| "text-Action-Light-Selected"
	| "text-Action-Light-Focus"
	| "text-Action-Light-Disabled"
	| "text-Action-Light-Disabled-background"
	| "text-OTHER-Instagram";
